[package]
name = "petabroad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18"
web-sys = "0.3.55"
mapex = {git = "https://github.com/alexmikhalevich/mapex.git", branch = "develop"}
